import re
from pathlib import Path
from typing import Self

from inflection import camelize

from pyfront.model import (
    Field,
    Front,
    GroupSymbol,
    KeywordSymbol,
    LabeledSymbol,
    Rule,
    SeparatedSymbol,
    StringSymbol,
    SymbolSequence,
)
from pyfront.parser_gen import GrammarBuilder
from pyfront.walk import walk_front, walk_symbol

from .grammar import Tokenizer, TokenType, parse_front
from .lexer import Lexer
from .parser import Parser


def _multi_char_replace_regex(text, replacements):
    pattern = "[" + re.escape("".join(replacements.keys())) + "]"
    return re.sub(pattern, lambda m: replacements[m.group()], text)


def _make_token_name(string: str) -> str:
    """Convert a string into a valid token name."""
    replacements = {
        '"': "DQUOTE",
        "-": "DASH",
        ",": "COMMA",
        ";": "SEMICOLON",
        ":": "COLON",
        "!": "EXCLAMATION",
        ".": "DOT",
        "'": "QUOTE",
        "(": "LPAREN",
        ")": "RPAREN",
        "[": "LBRACKET",
        "]": "RBRACKET",
        "{": "LBRACE",
        "}": "RBRACE",
        "@": "AT",
        "*": "ASTERISK",
        "/": "SLASH",
        "\\": "BSLASH",
        "&": "AMPERSAND",
        "#": "HASH",
        "%": "PERCENT",
        "`": "BACKTICK",
        "^": "CARET",
        "+": "PLUS",
        "<": "LESS_THAN",
        "=": "EQUALS",
        ">": "GREATER_THAN",
        "|": "PIPE",
        "~": "TILDE",
        "$": "DOLLAR",
    }
    return _multi_char_replace_regex(string.upper(), replacements)


class SymbolTable:
    def __init__(self, front: Front):
        self.front = front
        self.adding = True
        self.symbols = {
            "Ident": None,
            "Int": None,
            "String": None,
            "Float": None,
        }

    def add_symbol(self, name: str, symbol) -> None:
        if self.adding:
            if name in self.symbols:
                raise ValueError(f"Duplicate symbol name: {name}")
            self.symbols[name] = symbol

    def get_symbol[T](self, name: str, type: type[T]) -> T:
        symbol = self.symbols.get(name)
        if symbol is not None and not isinstance(symbol, type):
            raise ValueError(f"Symbol '{name}' is not of type {type.__name__}.")
        return symbol

    def pre_rule(self, rule: Rule) -> None:
        if rule.is_ref:
            return
        self.add_symbol(rule.name, rule)
        rule.super_rule = self.get_symbol(rule.super_type, Rule) if rule.super_type else None

    def pre_keyword_symbol(self, symbol: KeywordSymbol) -> None:
        symbol.rule = self.get_symbol(symbol.keyword, Rule)

    @classmethod
    def populate(cls, front: Front) -> Self:
        symbol_table = cls(front)
        walk_front(front, symbol_table)
        symbol_table.adding = False
        walk_front(front, symbol_table)
        return symbol_table


class Generator:
    def __init__(self) -> None:
        self.output = ""

    def print(self, text: str = "") -> None:
        self.output += text + "\n"

    def emit(self, path: Path) -> None:
        path.write_text(self.output, encoding="utf-8")


class CollectTokens(Generator):
    def __init__(self, front: Front) -> None:
        super().__init__()
        self.tokens = {}
        self.front = front

    def pre_string_symbol(self, symbol: StringSymbol) -> None:
        token = symbol.value[1:-1]
        token_name = _make_token_name(token)
        if token_name in self.tokens and self.tokens[token_name] != token:
            raise ValueError(f"Duplicate token name generated from string symbol: {token_name}")
        self.tokens[token_name] = token

    def collect(self) -> Self:
        walk_front(self.front, self)
        return self

    def generate_header(self) -> None:
        self.print("# Generated by pyfront. Do not edit.")
        self.print("from enum import Enum, auto")
        self.print()

    def generate_token_type_class(self, front: Front, output_dir: Path) -> None:
        self.print("class TokenType(Enum):")
        for name in sorted(self.tokens):
            self.print(f"    {name} = auto()")
        self.print()

    def generate_tokenizer(self, front: Front, output_dir: Path) -> None:
        self.print("class Tokenizer:")
        self.print("    TokenRegex = {")
        for token_name, token in sorted(self.tokens.items()):
            token_re = re.escape(token)
            if token[-1:].isalnum():
                token_re += r"(?![a-zA-Z0-9_])"
            self.print(f"        TokenType.{token_name}: r'{token_re}',")
        self.print("         # Valued tokens")
        self.print(r'        TokenType.IDENT: r"[a-zA-Z_][a-zA-Z0-9_]*",')
        self.print(r'        TokenType.FLOAT: r"\d+\.\d+",')
        self.print(r'        TokenType.INT: r"\d+",')
        self.print('        TokenType.STRING: r\'"[^"]*"\',')

        self.print("    }")
        self.print()
        self.print("    WhitespaceRegexs = {")
        self.print(r'        r"\s+": "whitespace",')
        self.print(r'        r"//.*": "single-line comment",')
        self.print(r'        r"/\*[\s\S]*?\*/": "multi-line comment",')
        self.print("    }")
        self.print()


class Normalize:
    def __init__(self, front: Front) -> None:
        self.front = front
        self.current_label: list[str] = []
        self.current_rule: Rule | None = None

    def pre_rule(self, rule: Rule) -> None:
        self.current_rule = rule
        new_rules = []
        for alt in rule.alts or []:
            if not alt.is_ref:
                alt.super_type = self.current_rule.name
                alt.super_rule = self.current_rule

                self.front.rules.append(alt)
                new_rules.append(
                    Rule(
                        is_root=False,
                        name=alt.name,
                        super_type=None,
                        fields=[],
                        terms=SymbolSequence(symbols=[]),
                        is_ref=True,
                    )
                )
            else:
                new_rules.append(alt)

        rule.alts = new_rules

    def pre_labeled_symbol(self, symbol: LabeledSymbol) -> None:
        self.current_label.append(symbol.label)

    def post_labeled_symbol(self, symbol: LabeledSymbol) -> None:
        self.current_label.pop()
        symbol.type = symbol.symbol.type

    def post_keyword_symbol(self, symbol: KeywordSymbol) -> None:
        sym_type = symbol.keyword
        match sym_type:
            case "Ident":
                sym_type = "str"
            case "Int":
                sym_type = "int"
            case "Float":
                sym_type = "float"
            case "String":
                sym_type = "str"
            case "Bool":
                sym_type = "bool"
        symbol.type = [sym_type]

    def post_string_symbol(self, symbol: StringSymbol) -> None:
        symbol.type = []

    def post_separated_symbol(self, symbol: SeparatedSymbol) -> None:
        symbol.type = ["list", *symbol.symbol.type]

    def post_symbol_sequence(self, symbol: SymbolSequence) -> None:
        symbol.type = [[sym.type for sym in symbol.symbols]]

    def post_group_symbol(self, symbol: GroupSymbol) -> None:
        if symbol.multiple:
            symbol.type = ["list", symbol.symbols.type]
        elif symbol.optional:
            symbol.type = ["Optional", symbol.symbols.type]
        else:
            symbol.type = [*symbol.symbols.type]

    def run(self) -> None:
        walk_front(self.front, self)


class GenerateSymbolType(Generator):
    def __init__(self) -> None:
        self.types = []

    def pre_keyword_symbol(self, symbol) -> None:
        sym_type = symbol.keyword
        match sym_type:
            case "Ident":
                sym_type = "str"
            case "Int":
                sym_type = "int"
            case "Float":
                sym_type = "float"
            case "String":
                sym_type = "str"
            case "Bool":
                sym_type = "bool"
        self.types.append(sym_type)

    def pre_separated_symbol(self, symbol) -> None:
        self.types.append("list")

    def pre_group_symbol(self, symbol) -> None:
        if symbol.multiple:
            self.types.append("list")
        elif symbol.optional:
            self.types.append("Optional")

    @classmethod
    def run(cls, symbol) -> str:
        gen = cls()
        walk_symbol(symbol, gen)
        sym_type = gen.types[-1]
        for t in reversed(gen.types[:-1]):
            if t == "Optional":
                sym_type = f"{sym_type} | None"
            else:
                sym_type = f"{t}[{sym_type}]"
        if sym_type == "Optional":
            sym_type = "bool"
        return sym_type


class GenerateModel(Generator):
    def __init__(self, front: Front) -> None:
        super().__init__()
        self.front = front
        self.current_rule: Rule | None = None
        self.has_fields = False
        self.print("# Generated by pyfront. Do not edit.")
        self.print("from dataclasses import dataclass")
        self.print()
        self.print()

    def pre_field(self, field: Field) -> None:
        sym_type = GenerateSymbolType.run(field.type)
        self.print(f"    {field.name}: {sym_type}")
        self.has_fields = True

    def pre_labeled_symbol(self, symbol) -> None:
        sym_type = GenerateSymbolType.run(symbol.symbol)
        super_rule = self.current_rule.super_rule if self.current_rule else None
        if super_rule and symbol.label in [f.name for f in super_rule.fields]:
            pass  # Inherited from super_rule.name
        else:
            self.print(f"    {symbol.label}: {sym_type}")
            self.has_fields = True

    def pre_rule(self, rule: Rule) -> None:
        if rule.is_ref:
            return
        self.current_rule = rule
        super_suffix = f"({rule.super_type})" if rule.super_type else ""
        self.print("@dataclass")
        self.print(f"class {rule.name}{super_suffix}:")
        self.has_fields = False

    def post_rule(self, rule: Rule) -> None:
        if rule.is_ref:
            return
        if not self.has_fields:
            self.print("    pass")
        self.print()
        self.print()
        self.current_rule = None

    def run(self) -> Self:
        walk_front(self.front, self)
        return self


class GenerateParser(Generator):
    def __init__(self, front: Front) -> None:
        super().__init__()
        self.front = front

    def run(self) -> Self:
        self.print("from .model import (")
        for rule in self.front.rules:
            self.print(f"    {camelize(rule.name)},")
        self.print(")\n")
        grammar_builder = GrammarBuilder()
        grammar_builder.build(self.front)
        self.print(grammar_builder.generate_code())
        return self


def run_generate(front_file: Path, output_dir: Path) -> None:
    """Read a .front file and write generation output into the output directory."""
    if front_file.suffix.lower() != ".front":
        raise ValueError("Input file must use the .front extension.")

    source = front_file.read_text(encoding="utf-8")

    parser = Parser(Lexer(Tokenizer(), source, eof_token=TokenType._EOF))
    front = parse_front(parser)
    SymbolTable.populate(front)
    Normalize(front).run()

    collector = CollectTokens(front).collect()
    collector.generate_header()
    collector.generate_token_type_class(front, output_dir)
    collector.generate_tokenizer(front, output_dir)

    model_generator = GenerateModel(front).run()
    parser_generator = GenerateParser(front).run()

    output_dir.mkdir(parents=True, exist_ok=True)

    collector.emit(output_dir / "grammar.py")
    model_generator.emit(output_dir / "model.py")
    parser_generator.emit(output_dir / "parser.py")
