from typing import Self

from pyfront.generate.emitter import Emitter
from pyfront.lang import model as gm
from pyfront.types import model as types
from pyfront.types.types_builder import BuildTypes

from ._base import GeneratorBase


class GenerateModel(GeneratorBase):
    _python_type_map = {
        "Bool": "bool",
        "Float": "float",
        "Ident": "str",
        "Int": "int",
        "String": "str",
    }

    def __init__(self, front: gm.Front, emitter: Emitter) -> None:
        super().__init__(emitter)
        self.front = front

    def _gen_type(self, type: types.Type) -> str:
        match type:
            case types.BuiltinType():
                return self._python_type_map[type.name]
            case types.RecordType():
                return type.name
            case types.ListType(inner_type=inner):
                inner_str = self._gen_type(inner)
                return f"list[{inner_str}]"
            case types.OptionalType(inner_type=inner):
                inner_str = self._gen_type(inner)
                return f"{inner_str} | None"
            case _:
                raise ValueError(f"Unknown type: {type}")

    def _gen_expression(self, expr: gm.Expression) -> str:
        match expr:
            case gm.IdExpr(id=id):
                return f'"{id}"'
            case gm.StringExpr(value=value):
                return f'"{value}"'
            case gm.IntExpr(value=value):
                return str(value)
            case gm.FloatExpr(value=value):
                return str(value)
            case gm.TrueExpr():
                return "True"
            case gm.FalseExpr():
                return "False"
            case gm.NoneExpr():
                return "None"
            case _:
                raise ValueError(f"Unknown expression: {expr}")

    def run(self) -> Self:
        model = BuildTypes(self.front).run()
        self.emit("""
            # Generated by pyfront. Do not edit.
            from dataclasses import dataclass, field
            
            """)
        for record in model.records:
            self.emit("@dataclass")
            super_suffix = f"({record.super_type.name})" if record.super_type else ""
            self.emit(f"class {record.name}{super_suffix}:").indent()
            if not record.fields:
                self.emit("pass")
            for field in record.fields:
                if field.default is not None:
                    value_str = (
                        f" = field(kw_only=True, default={self._gen_expression(field.default)})"
                    )
                else:
                    value_str = ""
                self.emit(f"{field.name}: {self._gen_type(field.type)}{value_str}")
            self.dedent().emit("\n")
        return self
